name: QuML Code Coverage
on: [pull_request]
jobs:
  QUML-Code-Coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: 12.20.0
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: install Angular Globally
        run: npm install -g @angular/cli@9.1.15 --no-progress
      - name: npm install for demo
        run: npm install --no-progress
      - name: npm install for Library
        run: npm install ./projects/quml-library/ --no-progress 
      - name: Test QuML
        run: npm run test-lib-ci